# Современные методы анализа данных и машинного обучения, БИ

## НИУ ВШЭ, 2025-26 учебный год

## Групповой проект №1. Exploratory Data Analysis

## Общая информация

__Дата выдачи:__ 04.03.2026dsad

__Дедлайн по записи в таблицу:__ 4:00 15.03.2026

__Дедлайн по загрузке работ:__ 4:00 19.03.2026

__Защита проекта:__ 19.03.2026 - 21.03.2026

## Формат выполнения

Групповой проект представляет собой творческое инициативное групповое задание, которое выполняется студентами в командах от 3 до 6 человек. В то же время следует помнить, что чем больше в команде людей, тем выше предъявляются требования в целом к команде, а также к выполняемому ею проекту. Команды разрешается формировать из студентов разных групп.

При оценивании результатов выполнения проекта командой в обязательном порядке проверяется и учитывается в оценке вклад **каждого участника** в общую работу команды. Вследствие этого крайне важно ответственно подойти к выбору сокомандников, распределению обязанностей внутри команды, а также пресечению наличия "мертвых душ" в команде.

При необходимости команда большинством голосов имеет право исключить человека из команды **до защиты проекта**, сообщив об этом преподавателю, в случае если такой человек никак не проявлялся в ходе выполнения проекта и являлся как раз таки той самой "мертвой душой". Помните про эту возможность, поскольку наличие "мертвых душ" может негативно повлиять на качество и оценку для всего проекта и, как следствие, в целом для всей команды!

Запись составов команд осуществляется по ссылке в таблице:

https://docs.google.com/spreadsheets/d/1tyI4TMQxR26aQX_bSyF5n4zzlJwG2j5ubyQ6GioeniY/edit?usp=sharing

## Отправка материалов группового проекта:

Во избежание использования при выполнении группового проекта генеративных моделей (ChatGPT и так далее) за рамками справочной и образовательной информации (то есть, например, для автоматической генерации кода по одному из этапов) **одному из участников команды** необходимо предварительно загрузить работу в систему [Anytask](https://anytask.org/). Наличие сгенерированного кода или любого другого случая "несанкционированного" использования нейросетей будет считаться плагиатом, и такой проект будет оценен в 0 баллов для всех участников. При отсутствии своевременно загруженных файлов с проектом команде также выставляется 0 за проект.

*Примечание: презентацию проекта загружать необязательно, важно отправить содержательные файлы с кодом*

## Оценивание и штрафы

Групповой проект оценивается исходя из устной защиты (презентации) командой выполненного ими проекта перед комиссией. Комиссия формируется из преподавателей курса, ассистентов курса, а также приглашенных экспертов из индустрии.

В рамках каждой защиты комиссия выставляет два типа оценок.

Первая оценка — это оценка для всего проекта в целом. Она ставится комиссией, исходя из глубины проработки командой предметной области, сложности применяемых в проекте инструментов, а также прочих аспектов, связанных с содержанием выполняемого в проекте ТЗ. При выставлении этой оценки комиссия ориентируется на критерии, более подробно представленные ниже в разделе "Критерии оценки проекта".

Вторая оценка — это индивидуальная оценка каждого участника команды. Именно эта оценка выставляется впоследствии в ведомость. Индивидуальная оценка участника команды определяется комиссией, исходя из того, насколько участник ориентируется в выполненном командой проекте, как он отвечает на адресованные персонально ему вопросы комиссии, насколько в принципе прослеживается его роль в проекте, а также исходя из других аспектов, связанных с участием конкретного человека в деятельности команды. Индивидуальная оценка не может превосходить оценку команды за проект в целом (первую оценку), однако, в случае когда участник спокойно и корректно отвечает на все адресованные ему вопросы, свободно ориентируется в материале и содержании выполненного проекта, а также когда его роль в работе команды не вызывает сомнений, — в таком случае индивидуальная оценка участника становится равной общей оценке команды за проект (т.е. в идеальном случае — вторая оценка равна первой оценке).

Во избежание субъективности и/или предвзятости оценки тех или иных членов комиссии в отношении тех или иных команд, а также каких-либо иных проявлений неравных условий — распределение команд между комиссиями осуществляется абсолютно рандомно с использованием средств библиотеки Numpy :)) — в качестве рэндом сида выступает дата, в которую производится распределение, например, `np.random.seed(04032026)`.

Обратите, пожалуйста, внимание на то, что бОльшая часть комиссий осуществляет приём проектов в очной форме, однако могут присутствовать и 1-2 комиссии, которые будут работать дистанционно с использованием средств видеосвязи. В случае попадания команды путем случайного распределения в комиссию, работающую в очной форме, **не допускается** какое-либо изменение формата проведения для команды на онлайн-режим, равно как и любые другие перемещения команд между комиссиями (смены комиссий), для сохранения честности и непредвзятости случайного распределения.

Явка студента на защиту проекта является обязательной; вклад студента без его присутствия не оценивается и автоматически является равным нулю. Для дистанционных комиссий дополнительным требованием является обязательное наличие включенной камеры в течение всего времени нахождения в конференции

## Описание задания

<img src="https://pp.userapi.com/c854528/v854528797/c62ce/FiPEibYUxJc.jpg" width="40%">

Netflix за последние десятки лет обзавелись большим количеством зрителей. С увеличением числа зрителей увеличилось и разнообразие шоу. Соответственно, перед аналитиками из киноиндустрии встала задача исследования данных с рейтингами различных сериалов.  

В данном задании вам предстоит провести визуальный анализ датасета **1000 Netflix Shows** (по состоянию на 11.06.2017) и сделать выводы.

### Описание признаков


* `title` - название шоу.
* `rating` - рейтинг шоу. Например: G, PG, TV-14, TV-MA.
* `ratingLevel` - описание рейтинговой группы и особенностей шоу.
* `ratingDescription` - рейтинг шоу, закодированный числом.
* `release year` - год выпуска шоу.
* `user rating score` - оценка пользователей.
* `user rating size` - общий рейтинг пользователей.

### Требования к проекту



В качестве результата выполнения группового проекта ваша команда должна получить презентацию и защитить ее перед комиссией.

Оформление презентации остаётся полностью на ваше усмотрение, но помните, что результат должен быть релевантен для демонстрации бизнес-заказчику — комиссию, принимающую вашу работу, правильнее всего воспринимать именно в таком качестве. Например, вставлять в презентацию строчки кода или злоупотреблять скринами блокнота не рекомендуется.

С точки зрения концепции выполнения проекта — вам необходимо принять на себя роль аналитиков: провести работу над признаками, исследовать информацию, содержащуюся в датасете,  выявить тенденции, тренды, факты из данных, а также, конечно, презентовать всё это в понятном виде.

Фактически, можно воспринимать этот проект в следующем ключе: к вам пришел некий бизнес-заказчик — например, это может быть непосредственно представитель Netflix, который хочет улучшить какие-то процессы; или какая-то компания, которая хочет снять какой-то новый проект и/или продать какой-то свой уже готовый продукт Netflix'у; или это может быть некая компания-конкурент Netflix'a, которая заинтересована в общем исследовании рынка; или абсолютно любой другой стейкхолдер в рамках данной отрасли — и этот заказчик просит вас проанализировать данные и извлечь на основе них какие-то полезные и значимые бизнес-инсайты для него. Разумеется, чем глубже, чем осмысленнее и чем нетривиальнее будут эти выводы, тем больше они вам заплатят :)

### Примеры вопросов и тем

Чтобы вы не начинали работу полностью с чистого листа, мы подобрали для вас некоторое количество опорных вопросов, с которых вы можете начать ваш первичный анализ.

**Внимание:** Эти вопросы лишь *приблизительные* и дают только *начальный вектор* для вашего исследования. Хотя качественно проработанные ответы на них и могут принести вам значительное количество первичных инсайтов и полезной информации, не стоит строить весь ваш проект вокруг только ответов на них. По возможности постарайтесь усовершенствовать и развить темы, затрагивающиеся в данных вопросах, либо вообще найти другие слои, которые в рамках них не рассматриваются (на самом деле таковых довольно много!)

Итак, сами вопросы:

- Сколько рейтинговых групп представлено в данных?
- Как рейтинговые группы отличаются друг от друга?
- Какие оценки пользователи ставят чаще всего?
- Какие оценки пользователи ставят в среднем?
- В какие годы были запущены шоу?
- Можно ли сделать вывод, что 2017 год успешнее для Netflix, чем 2016?
- Выберите любое шоу (например, самое понравившееся) и составьте его описательный портрет. На какие вопросы о нем вам было бы интересно ответить, если бы вы были заказчиком? Ответьте на эти вопросы :)
- Какие существуют признаки, не представленные в данных, но существенно влияющие на имеющиеся признаки?
- Как формируются оценки?
- Каким образом собирались сами данные?

Повторимся еще раз: это лишь *примерные вопросы*, для того чтобы дать вам начальный вектор, в котором вы могли бы двигаться. Вы можете отвечать или не отвечать на них по своему усмотрению, а также действовать таким образом и в том направлении, как полностью посчитаете нужным!

### Полезные замечания и советы

- Следите за тем, чтобы все графики на слайдах можно было прочитать даже без ваших комментариев;
- Не нужно делать просто текстовые слайды;
- Стройте свой анализ исходя из того, что ваша цель — представить полезную информацию для бизнеса;
- Любой хороший Data Scientist должен уметь работать в команде, поэтому распределение ваших усилий в проекте остается за вами, однако каждый участник должен уметь объяснять любую часть проекта;
- Не обязательно ограничиваться представленным датасетом. У вас есть весь интернет, чтобы найти дополнительную информацию и проверить ваши гипотезы. Дерзайте!

### Примерный скелет EDA

Опять-таки, чтобы вам не приходилось начинать написание кода с чистого листа, мы выстроили некий простейший скелет возможных этапов, которые вы могли бы включить в основу вашего первичного анализа.

Как вы уже, наверное, поняли, мы не настаиваем! :)

#### Скачайте данные
Загрузите данные, выполнив код ниже. Удалите нерелевантные признаки.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving NetflixShows.xlsx to NetflixShows.xlsx

In [ ]:
data = pd.read_excel("NetflixShows.xlsx")
del data['ratingDescription'], data['user rating size']

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              1000 non-null   object
 1   rating             1000 non-null   object
 2   ratingLevel        941 non-null    object
 3   release year       1000 non-null   int64
 4   user rating score  605 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 39.2+ KB

#### Удалите из данных дубликаты.
- Почему они возникли?
- Много ли их? В каких группах их больше всего?

## Удаление дубликатов

In [ ]:
duplicate_mask = data.duplicated(keep=False)

print(f'Кол-во дубликатов: {(duplicate_mask == True).sum()}')

Кол-во дубликатов: 744

In [ ]:
data['title'] = data['title'].astype(str)

In [ ]:
data[duplicate_mask].sort_values(by='title')

,title,rating,ratingLevel,release year,user rating score
295,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0
141,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0
41,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0
241,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0
497,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0
...,...,...,...,...,...
634,Zootopia,PG,"some thematic elements, rude humor and action",2016,97.0
691,Zootopia,PG,"some thematic elements, rude humor and action",2016,97.0
342,Zootopia,PG,"some thematic elements, rude humor and action",2016,97.0
736,Zootopia,PG,"some thematic elements, rude humor and action",2016,97.0
86,Zootopia,PG,"some thematic elements, rude humor and action",2016,97.0

Возможно дубликаты возниклы на этапе сбора данных, так как проследить прямую причину(на основе имеющихся данных) их возникновения невозможно, потому что дубликатам подверглись как сериалы, которые в теории могли иметь несколько сезоно, но в связи с существующеми колонками сезоны не отображаеются, так и фильмы, которые не могут иметь сезонов.

Команда смогла найти сайт с исходным файлом датасета - https://www.kaggle.com/datasets/chasewillden/netflix-shows/data

Там сказано, что датасет формировался на основе рекомендательной системы netflix, то-есть для нескольких исходных шоу были получены списки рекомендуемых похожих шоу. Так как одно и то же шоу могло быть рекомендовано для разных исходных шоу, оно могло попасть в датасет несколько раз, это и привело к появлению дубликатов.

In [ ]:
data = data.drop_duplicates()

(data.duplicated(keep=False)== True).sum()

np.int64(0)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 0 to 998
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              500 non-null    object
 1   rating             500 non-null    object
 2   ratingLevel        467 non-null    object
 3   release year       500 non-null    int64
 4   user rating score  256 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 23.4+ KB

##Удаление пропусков

Посмотрим кол-во пропусков в данных

In [ ]:
data.isna().sum()

title                  0
rating                 0
ratingLevel           33
release year           0
user rating score    244
dtype: int64

In [ ]:
data[data['user rating score'].isna()].head(10)

,title,rating,ratingLevel,release year,user rating score
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",2006,NaN
14,The Hunter,R,language and brief violence,2011,NaN
15,Lottie Dottie Chicken,TV-Y,Suitable for all ages.,2009,NaN
21,"ÌÒ Pai, ÌÒ - Look at This",TV-MA,For mature audiences. May not be suitable for...,2007,NaN
22,Nymphomaniac: Volume 1,NR,This movie has not been rated.,2013,NaN
28,The Seven Deadly Sins,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,NaN
29,Scream,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,NaN
31,OperaÌ¤Ìµes Especiais,TV-MA,NaN,2015,NaN
32,0.03,TV-MA,For mature audiences. May not be suitable for...,2016,NaN
34,Fearless,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,NaN

In [ ]:
data[data['ratingLevel'].isna()].head(10)

,title,rating,ratingLevel,release year,user rating score
25,Marvel's Iron Fist,TV-MA,NaN,2017,98.0
31,OperaÌ¤Ìµes Especiais,TV-MA,NaN,2015,NaN
39,Girlboss,TV-MA,NaN,2017,94.0
42,Sand Castle,TV-MA,NaN,2017,89.0
44,Sandy Wexler,TV-14,NaN,2017,92.0
45,O Amor no DivÌ£,TV-MA,NaN,2016,NaN
46,Stronger Than the World,NR,NaN,2016,NaN
48,Happily Married,TV-14,NaN,2015,NaN
49,Pandora,TV-MA,NaN,2016,NaN
85,Ingobernable,TV-MA,NaN,2017,96.0

Удалять строки не стоит, так как мы потеряем половину данных. Заполним пропуски в категориальной колонке ratingLevel категорией 'Unknown', а строки с пропусками в колонке user rating score удалим, так как она является нашей целью(target) и заполнив ее медианой или другим числовым значением испортим показания графиков

In [ ]:
data.loc[:,'ratingLevel'] = data['ratingLevel'].fillna('Unknown')
data_without_del = data
data = data.dropna()


data.isna().sum()

title                0
rating               0
ratingLevel          0
release year         0
user rating score    0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 256 entries, 0 to 979
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              256 non-null    object
 1   rating             256 non-null    object
 2   ratingLevel        256 non-null    object
 3   release year       256 non-null    int64
 4   user rating score  256 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 12.0+ KB

##Изучение данных

#### Сколько рейтинговых групп представлено в данных?

In [ ]:
print(f"рейтинговые группы: {data['rating'].unique()} \n кол-во рейтинговых групп: {len(data['rating'].unique())}")

рейтинговые группы: ['PG-13' 'TV-14' 'TV-PG' 'TV-MA' 'NR' 'TV-Y' 'TV-Y7-FV' 'PG' 'R' 'TV-G'
 'G' 'TV-Y7']
 кол-во рейтинговых групп: 12

#### Какие оценки пользователи ставят чаще?

- Постройте гистограмму оценок.
- Почему именно такие оценки ставят чаще всего?

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import plotly
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

In [ ]:
our_hist = go.Histogram(x = data['user rating score'], nbinsx=25, marker=dict(line=dict(color='LightSkyBlue', width=1))) #Кирилл добавил обводку

fig = go.Figure(data = our_hist)

fig.update_layout(
    title='Распределение оценок пользователей',
    xaxis_title='Оценка',
    yaxis_title='Кол-во'
)

fig.show()

Судя по гистограмме, чаще встречаются высокие оценки. Предположительно, это связано с тем, что в выборке преоладает популярный контент. Также пользователи скорее досмотрят и оценят то, что им понравилось.

In [ ]:
data.nlargest(10, columns='user rating score')

,title,rating,ratingLevel,release year,user rating score
41,13 Reasons Why,TV-MA,For mature audiences. May not be suitable for...,2017,99.0
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,98.0
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,2008,98.0
8,The Walking Dead,TV-MA,For mature audiences. May not be suitable for...,2015,98.0
10,Once Upon a Time,TV-PG,Parental guidance suggested. May not be suitab...,2016,98.0
25,Marvel's Iron Fist,TV-MA,Unknown,2017,98.0
27,The Flash,TV-PG,Parental guidance suggested. May not be suitab...,2016,98.0
62,Family Guy,TV-MA,For mature audiences. May not be suitable for...,2015,98.0
63,Criminal Minds,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,98.0
64,Friends,TV-14,Parents strongly cautioned. May be unsuitable ...,2003,98.0

##Изучение рейтинговых оценок

#### Выведите основную информацию об оценках пользователей
- Чему равны среднее, стандартное отклонение, минимум, максимум, медиана?
- Отличаются ли медиана и среднее?
- Могут ли данные характеристики значительно отличаться? Почему?

In [ ]:
print(f"Среднее: {data['user rating score'].mean()}")
print(f"Стандартное отклонение: {data['user rating score'].std()}")
print(f"Минимум: {data['user rating score'].min()}")
print(f"Максимум: {data['user rating score'].max()}")
print(f"Медиана: {data['user rating score'].median()}")

Среднее: 81.3984375
Стандартное отклонение: 12.730904096632221
Минимум: 55.0
Максимум: 99.0
Медиана: 83.5

Медиана и среднее отличаются на 2.1, при этом среднее значение меньше медианы. Это указывает на то, что распределение смещено в сторону меньших значений.
Медиана и среднее могут значительно отличаться при наличии выбросов. В этом случае среднее значение становится менее репрезентативным, так как на него сильно влияют экстремальные значения, которые могут существенно завышать или занижать среднее относительно основной массы данных. Медиана в такой ситуации является более устойчивой к выбросам характеристикой.

##Изучение дат выпуска тайтлов + выбросы

#### В какие годы были запущены шоу, представленные в датасете?

In [ ]:
data['release year'].unique()

array([2004, 2016, 2008, 2014, 2013, 2017, 2015, 2006, 2012, 2003, 2011,
       2010, 1998, 1999, 1978, 2007, 2009, 2005, 2001, 1993, 2002, 2000,
       1994, 1997, 1982, 1990, 1940, 1986, 1995, 1992, 1987, 1989])

#### Постройте график, показывающий распределение количества запущенных шоу в зависимости от года.

- Наблюдается ли рост?
- Есть ли выбросы?
- Что из себя представляют выбросы?
- Чем могут быть они вызваны?

Построим график распределения количества шоу по годам для нашего датасета и посмотрим, как распределяются данные в зависимости от года. В зависимости от этого посмотрим на данные и проанализируем результат наших действий.

In [ ]:
our_hist_1 = go.Histogram(x = data['release year'], nbinsx=125, marker=dict(line=dict(color='LightSkyBlue', width=1))) #Кирилл добавил обводку, если что можно откатить на nbinsx=25 и он будет брать периоды на 5 лет

fig = go.Figure(data = our_hist_1)

fig.update_layout(
    title='Распределение кол-ва выпущенных шоу по годам',
    xaxis_title='Год',
    yaxis_title='Кол-во',
)

fig.show()

In [ ]:
data[data['release year'] < 2000]

,title,rating,ratingLevel,release year,user rating score
250,The Waterboy,PG-13,language and some crude sexual humor,1998,82.0
251,10 Things I Hate About You,PG-13,"adult content, adult language and mild violence",1999,68.0
252,Grease,PG,Parental guidance suggested. May not be suitab...,1978,86.0
500,The Nightmare Before Christmas,PG,some scary images,1993,84.0
551,An Extremely Goofy Movie,G,General Audiences. Suitable for all ages.,1999,67.0
553,The Iron Giant,PG,fantasy action and mild language,1999,83.0
568,Goosebumps,TV-Y7,Suitable for children ages 7 and older,1998,88.0
600,The Little Rascals,PG,some rude dialogue,1994,86.0
601,Flubber,PG,slapstick action and mild language,1997,83.0
602,Tarzan,G,General Audiences. Suitable for all ages.,1999,95.0
651,Antz,PG,moderate adult language and intense action,1998,80.0
658,Annie,PG,adult content and mld violence,1982,68.0
670,The Magic School Bus,TV-Y,Suitable for all ages.,1997,81.0
700,Cool Runnings,PG,Parental guidance suggested. May not be suitab...,1993,81.0
701,Homeward Bound: The Incredible Journey,G,General Audiences. Suitable for all ages.,1993,96.0
703,Anastasia,G,General Audiences. Suitable for all ages.,1997,93.0
708,Missione Hamburger,PG,"language, some comic violence and mild sex-rel...",1997,75.0
749,The Real Ghostbusters,TV-Y7,Suitable for children ages 7 and older,1990,65.0
754,The Prince of Egypt,PG,intense scenes dealing with strong content,1998,81.0
759,Pocahontas II: Journey to a New World,TV-G,Suitable for all ages.,1998,64.0
761,Fantasia,G,General Audiences. Suitable for all ages.,1940,61.0
762,An American Tail,G,General Audiences. Suitable for all ages.,1986,67.0
766,Balto,G,General Audiences. Suitable for all ages.,1995,64.0
784,Animaniacs,TV-Y7,Suitable for children ages 7 and older,1997,72.0
805,FernGully: The Last Rainforest,G,General Audiences. Suitable for all ages.,1992,70.0
908,Harry and the Hendersons,PG,Parental guidance suggested. May not be suitab...,1987,58.0
962,Baby's Day Out,PG,mild language and comic action,1994,71.0
966,Blank Check,PG,Parental guidance suggested. May not be suitab...,1994,93.0
967,Heavyweights,PG,some rude language and pranks,1995,74.0
972,D2: The Mighty Ducks,PG,some mild language and rough hockey action,1994,70.0
973,"Honey, I Shrunk the Kids",PG,Parental guidance suggested. May not be suitab...,1989,80.0

Мы можем заметить масив фильмов, даты выпуска которых варируются 1940-1999 годами. В эти промежутки времени выходило гораздо меньше шоу, что говорит о маленьком количестве информации для анализа. Построим BoxPlot, чтобы убедиться в этом.

In [ ]:
fig = px.box(data_without_del, y='release year') #поменял на plotly
fig.show()

Можно заметить, некоторая часть шоу выпала за границы. Посмотрим, что это за значения, и выберем наши дальнейшие действия - считаем их выбросами, или нет.

In [ ]:
Q1 = data_without_del['release year'].quantile(0.25)
Q3 = data_without_del['release year'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1 =", Q1)
print("Q3 =", Q3)
print("IQR =", IQR)
print("Нижняя граница =", lower_bound)
print("Верхняя граница =", upper_bound)

Q1 = 2009.0
Q3 = 2016.0
IQR = 7.0
Нижняя граница = 1998.5
Верхняя граница = 2026.5

In [ ]:
outliers = data_without_del[
    (data_without_del['release year'] < lower_bound) |
    (data_without_del['release year'] > upper_bound)
]

print("Количество выбросов:", len(outliers))
outliers

Количество выбросов: 43

,title,rating,ratingLevel,release year,user rating score
250,The Waterboy,PG-13,language and some crude sexual humor,1998,82.0
252,Grease,PG,Parental guidance suggested. May not be suitab...,1978,86.0
500,The Nightmare Before Christmas,PG,some scary images,1993,84.0
506,The Smurfs and the Magic Flute,G,General Audiences. Suitable for all ages.,1976,NaN
507,We're Back! A Dinosaur's Story,G,General Audiences. Suitable for all ages.,1993,NaN
519,The Super Mario Bros. Super Show!,TV-Y7,Suitable for children ages 7 and older,1989,NaN
520,Power Rangers Zeo,TV-Y7-FV,Suitable for children ages 7 and older. Conte...,1996,NaN
563,Ninja Turtles: The Next Mutation,TV-Y7-FV,Suitable for children ages 7 and older. Conte...,1997,NaN
568,Goosebumps,TV-Y7,Suitable for children ages 7 and older,1998,88.0
600,The Little Rascals,PG,some rude dialogue,1994,86.0
601,Flubber,PG,slapstick action and mild language,1997,83.0
651,Antz,PG,moderate adult language and intense action,1998,80.0
658,Annie,PG,adult content and mld violence,1982,68.0
670,The Magic School Bus,TV-Y,Suitable for all ages.,1997,81.0
700,Cool Runnings,PG,Parental guidance suggested. May not be suitab...,1993,81.0
701,Homeward Bound: The Incredible Journey,G,General Audiences. Suitable for all ages.,1993,96.0
703,Anastasia,G,General Audiences. Suitable for all ages.,1997,93.0
708,Missione Hamburger,PG,"language, some comic violence and mild sex-rel...",1997,75.0
749,The Real Ghostbusters,TV-Y7,Suitable for children ages 7 and older,1990,65.0
753,Babe: Pig in the City,G,General Audiences. Suitable for all ages.,1998,NaN
754,The Prince of Egypt,PG,intense scenes dealing with strong content,1998,81.0
755,Paulie,PG,Parental guidance suggested. May not be suitab...,1998,NaN
759,Pocahontas II: Journey to a New World,TV-G,Suitable for all ages.,1998,64.0
761,Fantasia,G,General Audiences. Suitable for all ages.,1940,61.0
762,An American Tail,G,General Audiences. Suitable for all ages.,1986,67.0
763,Pooh's Grand Adventure: The Search for Christo...,G,General Audiences. Suitable for all ages.,1997,NaN
764,FernGully 2: The Magical Rescue,G,General Audiences. Suitable for all ages.,1998,NaN
766,Balto,G,General Audiences. Suitable for all ages.,1995,64.0
768,The Brave Little Toaster Goes to Mars,G,General Audiences. Suitable for all ages.,1998,NaN
769,The Brave Little Toaster to the Rescue,G,General Audiences. Suitable for all ages.,1997,NaN
771,An American Tail: Fievel Goes West,G,General Audiences. Suitable for all ages.,1991,NaN
772,The Last Unicorn,G,General Audiences. Suitable for all ages.,1982,NaN
777,Jetsons: The Movie,G,General Audiences. Suitable for all ages.,1990,NaN
784,Animaniacs,TV-Y7,Suitable for children ages 7 and older,1997,72.0
805,FernGully: The Last Rainforest,G,General Audiences. Suitable for all ages.,1992,70.0
815,The Very Hungry Caterpillar and Other Stories,TV-Y,Suitable for all ages.,1993,NaN
908,Harry and the Hendersons,PG,Parental guidance suggested. May not be suitab...,1987,58.0
951,Mr. Magoo,PG,mild language and action sequences,1997,NaN
962,Baby's Day Out,PG,mild language and comic action,1994,71.0
966,Blank Check,PG,Parental guidance suggested. May not be suitab...,1994,93.0
967,Heavyweights,PG,some rude language and pranks,1995,74.0
972,D2: The Mighty Ducks,PG,some mild language and rough hockey action,1994,70.0
973,"Honey, I Shrunk the Kids",PG,Parental guidance suggested. May not be suitab...,1989,80.0

По результатам boxplot видно, что в данных есть выбросы. Всего было найдено 43 выброса, и большинство связаны с очень старыми фильмами, которые сильно отличаются по году выпуска от основной части выборки. Среди них, например, Fantasia (1940), Grease (1978), Annie (1982), Harry and the Hendersons (1987) и другие фильмы конца XX века.

То есть выбросы в нашем случае — это не ошибки в датасете, а просто старые фильмы, которые попали в выборку вместе с более современными шоу. Основная часть контента в датасете относится к более новым годам, поэтому такие старые релизы сильно выбиваются из общего распределения.

Скорее всего, это связано с тем, что в каталоге Netflix есть не только новые фильмы и сериалы, но и более старая классика. То есть, это не аномалия данных, а особенность формирования выборки. Поэтому такие значения появились в данных и на boxplot отображаются как выбросы.

##Сравнение 2016 и 2017 года

#### Сравните среднюю оценку пользователей в 2016 со средней оценкой в 2017.
- Можно ли сделать вывод, что 2017 год успешнее для Netflix? ("Успешнее" значит, что пользователи в среднем ставили более высокие оценки)
- Как еще можно оценить "Успешность"?

Успешность Netflix можно также можно оценить по количеству просмотров или оценок. Однако для нашего тайтла мы можем оценить только по оценкам пользователей, поэтому будем использовать датасет с удаленными пропусками в колонке 'user rating score'

In [ ]:
data_2016 = data[data['release year'] == 2016]
data_2017 = data[data['release year'] == 2017]

In [ ]:
avg_2016 = data_2016['user rating score'].mean()
avg_2017 = data_2017['user rating score'].mean()

print(f"среднее 2016: {avg_2016}, среднее 2017: {avg_2017}")

среднее 2016: 84.31395348837209, среднее 2017: 88.125

In [ ]:
med_2016 = data_2016['user rating score'].median()
med_2017 = data_2017['user rating score'].median()

print(f"медиана 2016: {med_2016}, медиана 2017: {med_2017}")

медиана 2016: 89.0, медиана 2017: 90.5

In [ ]:
fig = make_subplots(rows=1, cols=2, subplot_titles=('Распределение оценок пользователей в 2016', 'Распределение оценок пользователей в 2017'))

fig.add_trace(
    go.Histogram(x=data_2016['user rating score'], name='Распределение оценок пользователей в 2016', nbinsx=25,
                 marker=dict(color='Blue', line=dict(color='LightSkyBlue', width=1))),
    row=1, col=1,
)

fig.add_trace(
    go.Histogram(x=data_2017['user rating score'], name='Распределение оценок пользователей в 2017', nbinsx=25,
                 marker=dict(color='Green', line=dict(color='LightSkyBlue', width=1))),
    row=1, col=2
)

fig.update_xaxes(title_text='Оценка', row=1, col=1)
fig.update_xaxes(title_text='Оценка', row=1, col=2)

fig.update_yaxes(title_text='Количество релизов', row=1, col=1)
fig.update_yaxes(title_text='Количество релизов', row=1, col=2)

In [ ]:
print(f"Кол-во релизов в 2016: {data_2016.shape[0]} \nКол-во релизов в 2017: {data_2017.shape[0]}")

Кол-во релизов в 2016: 86
Кол-во релизов в 2017: 16

In [ ]:
std_2016 = data_2016['user rating score'].std()
std_2017 = data_2017['user rating score'].std()

In [ ]:
print(f"Кол-во релизов в 2016: {data_2016.shape[0]}, кол-во релизов в 2017: {data_2017.shape[0]}")
print(f"среднее 2016: {avg_2016}, среднее 2017: {avg_2017}")
print(f"медиана 2016: {med_2016}, медиана 2017: {med_2017}")
print(f"отклонение 2016: {std_2016}, отклонение 2017: {std_2017}")

Кол-во релизов в 2016: 86, кол-во релизов в 2017: 16
среднее 2016: 84.31395348837209, среднее 2017: 88.125
медиана 2016: 89.0, медиана 2017: 90.5
отклонение 2016: 12.599030427594746, отклонение 2017: 8.585841057617284

In [ ]:
diff = pd.DataFrame({
    'год': [2016, 2017],
    'кол-во релизов': [data_2016.shape[0], data_2017.shape[0]],
    'среднее': [avg_2016, avg_2017],
    'медиана': [med_2016, med_2017],
    'отклонение': [std_2016, std_2017]
})
diff

    год  кол-во релизов    среднее  медиана  отклонение
0  2016              86  84.313953     89.0   12.599030
1  2017              16  88.125000     90.5    8.585841

Среднее и медиана в 2017 году выше, что означает более высокую пользовательскую оценку релизам вышедшим в 2017, чем в 2016. Также отклонение в 2017 меньше чем в 2016, значит оценки пользователей более стабильные в 2017. Но число релизов в 2017 значительно меньше. Это связано с тем, что датасет был сформирован до завершения 2017 года(11.06.2017), поэтому в нём не присутствуют все релизы этого года.

Однозначно считать 2017 год успешнее чем 2016 нельзя, так как данные за 2017 не полные

##Распределение рейтинговых групп

#### Как нагляднее будет показать распределение пользователей по рейтинговым группам?

Ниже представлены два графика, показывающие распределение шоу по рейтинговым группам. Какой тип графика визуально более интерпретируемый? ([Подсказка](https://sun9-40.userapi.com/c854228/v854228652/c754f/j6z5gMjJy2k.jpg))  
Постройте самостоятельно график, который считаете более интерпретируемым. Сделайте вывод.

Может быть, лучше использовать и какие-то другие, еще более продвинутые визуализации?

![Charts](https://pp.userapi.com/c852024/v852024281/1a53b1/jSOsBIhxK3U.jpg)

Мы считаем, что оба графика имеют свои недостатки. Первый график легче воспринять, но на нем некоторые значения пересекаются и не так просто вывести абсолютные значения, в то время как на втором они есть, но например для демострации заказчикам этот график выглядит не очень. Мы предлагаем использовать круговую диаграмму, реализуемую библиотекой Plotly, там можно наводится на ячейки и смотреть долю и числовое значение, а так же интерактивный функционал позволяет скрывать ненужные данные.

In [ ]:
data_rating_sorted = data.groupby('rating').size()
data_rating_sorted = data_rating_sorted.sort_values(ascending=False)
data_rating_sorted = data_rating_sorted.reset_index(name='count')
data_rating_sorted

      rating  count
0      TV-14     77
1         PG     48
2      TV-MA     40
3      TV-PG     21
4          G     19
5       TV-G     11
6      PG-13      9
7   TV-Y7-FV      8
8       TV-Y      8
9          R      7
10     TV-Y7      6
11        NR      2

In [ ]:
fig = px.pie(data_rating_sorted, values='count', names='rating', title='Распределение рейтинговых групп')
fig.show()

In [ ]:
our_bar = go.Bar(x = data_rating_sorted['rating'], y = data_rating_sorted['count'], marker=dict(line=dict(color='LightSkyBlue', width=1)))

fig = go.Figure(data = our_bar)

fig.update_layout(
    title='Распределение рейтинговых групп',
    xaxis_title='Рейтинг',
    yaxis_title='Кол-во тайтлов'
)

fig.show()

Такое распределение рейтингов связано со способом формирования данного датасета. Автор выбрал по 4 тайтла в разных возрастных рейтингах и на основе них с помощью рекомендательной системы нетфликс были подобраны похожие сериалы. Так как рекомендательные алгоритмы подбирают контент с похожими характеристиками, в том числе с близкими возрастными рейтингами, итоговое распределение рейтингов в датасете будет смещено в сторону рейтингов исходных фильмов/сериалов.

##Добавление данных из другого датасета

Команда решила дополнить наш файл новыми сведениями о тайтлах на основе данного датасета: https://www.kaggle.com/datasets/thedevastator/the-ultimate-netflix-tv-shows-and-movies-dataset/data?select=raw_titles.csv

title: The title of the movie or TV show. (String)

type: The type of the movie or TV show. (String)

release_year: The year the movie or TV show was released. (Integer)

age_certification: The age certification of the movie or TV show. (String)

runtime: The runtime of the movie or TV show. (Integer)

genres: The genres of the movie or TV show. (String)

production_countries: The production countries of the movie or TV show. (String)

seasons: The number of seasons of the TV show. (Integer)

imdb_score: The IMDB score of the movie or TV show. (Float)

imdb_votes: The number of IMDB votes of the movie or TV show. (Integer)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving raw_titles.csv to raw_titles.csv

In [ ]:
data_1 = data.copy()

In [ ]:
data_2 = pd.read_csv("raw_titles.csv")

In [ ]:
data_2.head()

,index,id,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
0,0,ts300399,Five Came Back: The Reference Films,SHOW,1945,TV-MA,48,['documentation'],['US'],1.0,NaN,NaN,NaN
1,1,tm84618,Taxi Driver,MOVIE,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0
2,2,tm127384,Monty Python and the Holy Grail,MOVIE,1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0
3,3,tm70993,Life of Brian,MOVIE,1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0
4,4,tm190788,The Exorcist,MOVIE,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0

In [ ]:
data_1.head()

,title,rating,ratingLevel,release year,user rating score
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",2004,82.0
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,98.0
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,2008,98.0
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,2014,94.0
5,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,95.0

In [ ]:
data_2[['title', 'release_year']].duplicated().sum()

np.int64(4)

In [ ]:
data_2 = data_2.drop_duplicates(subset=['title','release_year'])

In [ ]:
data_1['title'] = data_1['title'].str.strip().str.lower()
data_2['title'] = data_2['title'].str.strip().str.lower()

In [ ]:
data_new = data_1.merge(data_2, on=['title'], how = 'left')
data_new.head()

,title,rating,ratingLevel,release year,user rating score,index,id,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
0,white chicks,PG-13,"crude and sexual humor, language and some drug...",2004,82.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,grey's anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,98.0,247.0,ts21469,SHOW,2005.0,TV-14,49.0,"['drama', 'romance']",['US'],18.0,tt0413573,7.6,293618.0
2,prison break,TV-14,Parents strongly cautioned. May be unsuitable ...,2008,98.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,how i met your mother,TV-PG,Parental guidance suggested. May not be suitab...,2014,94.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,95.0,253.0,ts21465,SHOW,2005.0,TV-14,45.0,"['scifi', 'thriller', 'drama', 'fantasy', 'hor...",['US'],15.0,tt0460681,8.5,428639.0

In [ ]:
data_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 257 non-null    object
 1   rating                257 non-null    object
 2   ratingLevel           257 non-null    object
 3   release year          257 non-null    int64
 4   user rating score     257 non-null    float64
 5   index                 85 non-null     float64
 6   id                    85 non-null     object
 7   type                  85 non-null     object
 8   release_year          85 non-null     float64
 9   age_certification     80 non-null     object
 10  runtime               85 non-null     float64
 11  genres                85 non-null     object
 12  production_countries  85 non-null     object
 13  seasons               70 non-null     float64
 14  imdb_id               83 non-null     object
 15  imdb_score            83 non-null     float64
 16  imdb_votes            83 non-null     float64
dtypes: float64(7), int64(1), object(9)
memory usage: 34.3+ KB

In [ ]:
data_new = data_new.drop(columns=['index','id','release_year'])

In [ ]:
data_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 256 entries, 0 to 979
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              256 non-null    object
 1   rating             256 non-null    object
 2   ratingLevel        256 non-null    object
 3   release year       256 non-null    int64
 4   user rating score  256 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 12.0+ KB

In [ ]:
data_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 257 non-null    object
 1   rating                257 non-null    object
 2   ratingLevel           257 non-null    object
 3   release year          257 non-null    int64
 4   user rating score     257 non-null    float64
 5   index                 85 non-null     float64
 6   id                    85 non-null     object
 7   type                  85 non-null     object
 8   release_year          85 non-null     float64
 9   age_certification     80 non-null     object
 10  runtime               85 non-null     float64
 11  genres                85 non-null     object
 12  production_countries  85 non-null     object
 13  seasons               70 non-null     float64
 14  imdb_id               83 non-null     object
 15  imdb_score            83 non-null     float64
 16  imdb_votes            83 non-null     float64
dtypes: float64(7), int64(1), object(9)
memory usage: 34.3+ KB

##График распредление тайтлов по странам производства

In [ ]:
our_hist = go.Histogram(x = data_new['production_countries'], marker=dict(line=dict(color='LightSkyBlue', width=1)))

fig = go.Figure(data = our_hist)

fig.update_layout(
    title='Распределение фильмов по стране производства',
    xaxis_title='Страны',
    yaxis_title='Кол-во'
)

fig.show()

##Сравнение двух сериалов

#### Теперь вам нужно выбрать любое из представленных шоу и при помощи изученных инструментов составить описательный портрет этого шоу :)

Аналитики и Data Scientist-ы очень любят все сравнивать, поэтому при составлении описательного портрета рекомендуем вам сравнить выбранное шоу с другими по каким-либо характеристикам.

Составим портрет двух тайтлов и сравним их между собой.

In [ ]:
data_new

,title,rating,ratingLevel,release year,user rating score,index,id,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
0,white chicks,PG-13,"crude and sexual humor, language and some drug...",2004,82.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,grey's anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,98.0,247.0,ts21469,SHOW,2005.0,TV-14,49.0,"['drama', 'romance']",['US'],18.0,tt0413573,7.6,293618.0
2,prison break,TV-14,Parents strongly cautioned. May be unsuitable ...,2008,98.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,how i met your mother,TV-PG,Parental guidance suggested. May not be suitab...,2014,94.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,95.0,253.0,ts21465,SHOW,2005.0,TV-14,45.0,"['scifi', 'thriller', 'drama', 'fantasy', 'hor...",['US'],15.0,tt0460681,8.5,428639.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,blank check,PG,Parental guidance suggested. May not be suitab...,1994,93.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,heavyweights,PG,some rude language and pranks,1995,74.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,d2: the mighty ducks,PG,some mild language and rough hockey action,1994,70.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,"honey, i shrunk the kids",PG,Parental guidance suggested. May not be suitab...,1989,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,h2o: just add water,TV-PG,Parental guidance suggested. May not be suitab...,2009,74.0,370.0,ts21706,SHOW,2006.0,TV-PG,25.0,"['drama', 'scifi', 'fantasy', 'family']",['AU'],3.0,tt0491603,7.2,14782.0

In [ ]:
data_new.dropna()

,title,rating,ratingLevel,release year,user rating score,index,id,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
1,grey's anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,98.0,247.0,ts21469,SHOW,2005.0,TV-14,49.0,"['drama', 'romance']",['US'],18.0,tt0413573,7.6,293618.0
4,supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,95.0,253.0,ts21465,SHOW,2005.0,TV-14,45.0,"['scifi', 'thriller', 'drama', 'fantasy', 'hor...",['US'],15.0,tt0460681,8.5,428639.0
5,breaking bad,TV-MA,For mature audiences. May not be suitable for...,2013,97.0,243.0,ts4,SHOW,2008.0,TV-MA,48.0,"['drama', 'thriller', 'crime']",['US'],5.0,tt0903747,9.5,1727694.0
6,the vampire diaries,TV-14,Parents strongly cautioned. May be unsuitable ...,2017,91.0,272.0,ts21247,SHOW,2009.0,TV-14,42.0,"['scifi', 'drama', 'thriller', 'fantasy', 'hor...",['US'],8.0,tt1405406,7.7,310776.0
7,the walking dead,TV-MA,For mature audiences. May not be suitable for...,2015,98.0,244.0,ts9,SHOW,2010.0,TV-MA,46.0,"['action', 'drama', 'scifi', 'thriller', 'horr...",['US'],11.0,tt1520211,8.2,945125.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,dreamworks shrek's swamp stories,TV-PG,Parental guidance suggested. May not be suitab...,2008,56.0,426.0,ts121176,SHOW,2010.0,TV-PG,24.0,"['horror', 'music', 'animation', 'comedy', 'fa...",['US'],1.0,tt6950338,6.5,330.0
221,the magic school bus,TV-Y,Suitable for all ages.,1997,81.0,121.0,ts22193,SHOW,1994.0,TV-Y,26.0,"['scifi', 'comedy', 'family', 'fantasy', 'anim...","['US', 'CA']",4.0,tt0108847,7.8,9708.0
222,sofia the first,TV-Y,Suitable for all ages.,2015,82.0,967.0,ts20281,SHOW,2013.0,TV-Y,24.0,"['family', 'fantasy', 'animation']",['US'],4.0,tt2136138,6.8,2915.0
234,bunk'd,TV-G,Suitable for all ages.,2016,61.0,1320.0,ts36046,SHOW,2015.0,TV-G,24.0,"['comedy', 'family', 'drama']",['US'],5.0,tt4591680,5.3,3174.0
256,h2o: just add water,TV-PG,Parental guidance suggested. May not be suitab...,2009,74.0,370.0,ts21706,SHOW,2006.0,TV-PG,25.0,"['drama', 'scifi', 'fantasy', 'family']",['AU'],3.0,tt0491603,7.2,14782.0

In [ ]:
data_new[data_new['title'] == 'stranger things']

,title,rating,ratingLevel,release year,user rating score,index,id,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
49,stranger things,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,90.0,1219.0,ts38796,SHOW,2016.0,TV-14,52.0,"['scifi', 'drama', 'fantasy', 'horror', 'thril...",['US'],5.0,tt4575572,8.7,989090.0

In [ ]:
data_new[data_new['title'] == 'breaking bad']

,title,rating,ratingLevel,release year,user rating score,index,id,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
5,breaking bad,TV-MA,For mature audiences. May not be suitable for...,2013,97.0,243.0,ts4,SHOW,2008.0,TV-MA,48.0,"['drama', 'thriller', 'crime']",['US'],5.0,tt0903747,9.5,1727694.0

Проведем анализ двух сериалов: stranger things и breaking bad

In [ ]:
mask = (data_new['title'] == 'breaking bad') | (data_new['title'] == 'stranger things')
compare_table = data_new[mask][['title','release year','user rating score','imdb_score','imdb_votes','runtime','seasons']]
compare_table

,title,release year,user rating score,imdb_score,imdb_votes,runtime,seasons
5,breaking bad,2013,97.0,9.5,1727694.0,48.0,5.0
49,stranger things,2016,90.0,8.7,989090.0,52.0,5.0

Breaking bad имеет более высокий рейтинг как на платформе нетфликс(примерно на 7 пунктов больше), так и на сервисе imdb, это может говорить о более успешном тайтле. Также людей оставивших свою рейтинговую оценку на сериал breaking bad почти в два раза больше чем людей оставивших оценку на stranger things. Серии в stranger things в среднем на 4 минуты продолжительнее чем в breaking bad. Оба сериала имеют 5 сезонов.

In [ ]:
fig = make_subplots(rows=1, cols=2, subplot_titles=('Оценки на netflix', 'Оценки на IMDb * 10'))

fig.add_trace(
    go.Bar(x = compare_table['title'], y = compare_table['user rating score'], name='Оценка netflix', marker=dict(color='Blue',
                                                                                                                  line=dict(color='LightSkyBlue', width=1))),
    row=1, col=1,
)

fig.add_trace(
    go.Bar(x = compare_table['title'], y = compare_table['imdb_score']*10, name='Оценка IMDb * 10',marker=dict(color='Green',
                                                                                                               line=dict(color='LightSkyBlue', width=1))),
    row=1, col=2
)

fig.show()

In [ ]:
our_bar = go.Bar(x = compare_table['title'], y = compare_table['imdb_votes'], marker=dict(line=dict(color='LightSkyBlue', width=1)))

fig = go.Figure(data = our_bar)

fig.update_layout(
    title='Количество голосов',
    xaxis_title='Сериал',
    yaxis_title='Количество'
)

fig.show()

In [ ]:
our_bar = go.Bar(x = compare_table['title'], y = compare_table['runtime'], marker=dict(line=dict(color='LightSkyBlue', width=1)))

fig = go.Figure(data = our_bar)

fig.update_layout(
    title='Средняя длительность серий',
    xaxis_title='Сериал',
    yaxis_title='Минуты'
)

fig.show()

In [ ]:
breaking_bad = compare_table['title']=='breaking bad'
stranger_things = compare_table['title']=='stranger things'

In [ ]:
fig = go.Figure()

fig.add_trace(go.Scatter(x=data_new['imdb_votes'],
                         y=data_new['imdb_score'],
                         mode='markers',
                         text=data_new['title'],
                         marker=dict(size=10,color='crimson'),
                         name='Остальные сериалы'))
fig.add_trace(go.Scatter(x=compare_table[breaking_bad]['imdb_votes'],
                         y=compare_table[breaking_bad]['imdb_score'],
                         mode='markers+text',
                         text=['Breaking Bad'],
                         textposition="top center",
                         name='Breaking Bad',
                         marker=dict(size=20,color='Purple')))

fig.add_trace(go.Scatter(x=compare_table[stranger_things]['imdb_votes'],
                         y=compare_table[stranger_things]['imdb_score'],
                         mode='markers+text',
                         text=['Stranger Things'],
                         textposition="top center",
                         name='Stranger Things',
                         marker=dict(size=20,color='royalblue')))

fig.update_layout(
    title='Популярность и рейтинг сериалов',
    xaxis_title='Количество оценок',
    yaxis_title='Рейтинг IMDb',
    legend_title='Сериал',
)

fig.show()

Вывод по анализу:

Оба сериала являются популярными и высоко ценятся среди зрителей, но отличия между ними присутствуют. Breaking bad демонстрирует более высокие рейтинги как на нетфликсе, так и на IMDb. Также он имеет большее кол-во голосов, что говорит о большей популярность в сравнении с Stranger things. Stranger things имеет большую среднюю продолжительность серий. Breaking bad превосходит stranger things в показателях пользовательской оценки и популярности.

##Анализ распредления жанров среди тайтлов

Проанализируем наш датасет и узнаем, как распределены жанры по среднему рейтингу пользователей.

Для это сделаем небольшой FA. Мы решили разбить жанры с помощью OHE, чтобы вынести каждую категорию в свой столбец отдельно. Изначально жанры представлены как список строк, разобьем их и применим кодирование.

In [ ]:
import ast

data_new['genres'] = data_new['genres'].apply(lambda x: ast.literal_eval(x) if pd.notna(x) else []) #без такой штуки не работает так как там есть 'NaN'
# либо можно сразу шоу без жанров удалить и по идее норм без нее будет работать
# https://stackoverflow.com/questions/75011487/use-ast-literal-eval-on-all-columns-of-a-pandas-dataframe

In [ ]:
categorical_subset = (data_new['genres'].explode()) #раскрываем списки жанров
#https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.explode.html
categorical_subset = pd.get_dummies(categorical_subset)
features = pd.concat([data_new, categorical_subset], axis=1)
features

,title,rating,ratingLevel,release year,user rating score,index,id,type,release_year,age_certification,...,history,horror,music,reality,romance,scifi,sport,thriller,war,western
0,white chicks,PG-13,"crude and sexual humor, language and some drug...",2004,82.0,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
1,grey's anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,98.0,247.0,ts21469,SHOW,2005.0,TV-14,...,False,False,False,False,False,False,False,False,False,False
1,grey's anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,2016,98.0,247.0,ts21469,SHOW,2005.0,TV-14,...,False,False,False,False,True,False,False,False,False,False
2,prison break,TV-14,Parents strongly cautioned. May be unsuitable ...,2008,98.0,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
3,how i met your mother,TV-PG,Parental guidance suggested. May not be suitab...,2014,94.0,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,"honey, i shrunk the kids",PG,Parental guidance suggested. May not be suitab...,1989,80.0,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
256,h2o: just add water,TV-PG,Parental guidance suggested. May not be suitab...,2009,74.0,370.0,ts21706,SHOW,2006.0,TV-PG,...,False,False,False,False,False,False,False,False,False,False
256,h2o: just add water,TV-PG,Parental guidance suggested. May not be suitab...,2009,74.0,370.0,ts21706,SHOW,2006.0,TV-PG,...,False,False,False,False,False,True,False,False,False,False
256,h2o: just add water,TV-PG,Parental guidance suggested. May not be suitab...,2009,74.0,370.0,ts21706,SHOW,2006.0,TV-PG,...,False,False,False,False,False,False,False,False,False,False
256,h2o: just add water,TV-PG,Parental guidance suggested. May not be suitab...,2009,74.0,370.0,ts21706,SHOW,2006.0,TV-PG,...,False,False,False,False,False,False,False,False,False,False

Отлично, теперь узнаем среднюю оценку по жанрам

In [ ]:
genre_list = categorical_subset.columns
mean_ratings = {}
for genre in genre_list:
    mean_ratings[genre] = features[features[genre] == 1]['user rating score'].mean()
mean_ratings_df = (pd.DataFrame(mean_ratings.items(), columns=['genre', 'mean_rating']).sort_values(by='mean_rating', ascending=False))
mean_ratings_df

            genre  mean_rating
3           crime    88.714286
4   documentation    88.500000
16       thriller    88.000000
13        romance    87.000000
14          scifi    86.347826
0          action    85.900000
18        western    85.000000
10         horror    84.909091
5           drama    84.879310
9         history    84.000000
17            war    83.500000
8         fantasy    82.360000
2          comedy    80.675676
1       animation    78.555556
11          music    78.500000
12        reality    77.500000
6        european    77.428571
7          family    77.181818
15          sport    73.500000

Для того, чтобы оценивание было более объективным и не страдало из-за недостаточной выборки, мы посмотрим кол-во вхождений каждого жанра в наш датасет.

In [ ]:
counts = {}

for genre in genre_list:
    counts[genre] = features[genre].sum()
counts_df = pd.DataFrame(counts.items(), columns=['genre', 'count'])

filtered = mean_ratings_df.merge(counts_df, on='genre')
filtered

            genre  mean_rating  count
0           crime    88.714286     21
1   documentation    88.500000      4
2        thriller    88.000000     26
3         romance    87.000000      6
4           scifi    86.347826     23
5          action    85.900000     20
6         western    85.000000      2
7          horror    84.909091     11
8           drama    84.879310     58
9         history    84.000000      1
10            war    83.500000      4
11        fantasy    82.360000     25
12         comedy    80.675676     37
13      animation    78.555556     18
14          music    78.500000      4
15        reality    77.500000      2
16       european    77.428571      7
17         family    77.181818     22
18          sport    73.500000      2

Видим, что такие жанры как music, sport, history, western, war, встречаются намного реже, относительно других жанров, давайте для более объективной оценки их уберем.

In [ ]:
filtered = filtered[filtered['count'] > 10].sort_values(by='mean_rating', ascending=False)
filtered

        genre  mean_rating  count
0       crime    88.714286     21
2    thriller    88.000000     26
4       scifi    86.347826     23
5      action    85.900000     20
7      horror    84.909091     11
8       drama    84.879310     58
11    fantasy    82.360000     25
12     comedy    80.675676     37
13  animation    78.555556     18
17     family    77.181818     22

Визуализируем полученные результаты и сделаем вывод

In [ ]:
fig = px.scatter(filtered, x='genre', y='mean_rating', title='Средний рейтинг по жанрам', size='count', color='mean_rating')
fig.update_layout(template='plotly_white')

В результате анализа получается, что самые самый популярный и высоко оцененный жанр - это драма, фильмов снимают много и рейтинг достачно высокий, скорее всего это связано с тем, что то снять такое кино дешевле, чем крутой триллер или крайм, но из-за того, что тема драматургии интересна и вызывает отклик и эмоции у большого количества людей - оценки такие высокие, несмотря на то что снимают очень много подобного кино.

Так же можно отметить, что в самом низу по оценкам находятся "семейные жанры", они доступны даже большему кругу людей, но оценены ниже той же самой драмы из чего можно сделать вывод, что для людей важнее пережитые эмоции полученные при просмотре кино и комедии, анимационные фильмы и семеное кино больше расценивается как разгрузочный и более проходной контент.

На самом деле это далеко не все выводы, которые можно сделать из данного анализа.

##Анализ различия рейтингов Netflix и IMDb

Проанализируем наш датасет на различие рейтингов imdb и netflix

In [ ]:
ratings_df = data_new[['title', 'user rating score', 'imdb_score', 'imdb_votes', 'type', 'release year']]

ratings_df = ratings_df.rename(columns={'user rating score': 'netflix_score'})
ratings_df = ratings_df.dropna(subset=['netflix_score', 'imdb_score'])

ratings_df['netflix_score'] = ratings_df['netflix_score'] / 10

ratings_df

,title,netflix_score,imdb_score,imdb_votes,type,release year
1,grey's anatomy,9.8,7.6,293618.0,SHOW,2016
4,supernatural,9.5,8.5,428639.0,SHOW,2016
5,breaking bad,9.7,9.5,1727694.0,SHOW,2013
6,the vampire diaries,9.1,7.7,310776.0,SHOW,2017
7,the walking dead,9.8,8.2,945125.0,SHOW,2015
...,...,...,...,...,...,...
222,sofia the first,8.2,6.8,2915.0,SHOW,2015
224,paddington,7.0,7.2,111092.0,MOVIE,2014
234,bunk'd,6.1,5.3,3174.0,SHOW,2016
250,corpse bride,9.1,7.3,265023.0,MOVIE,2005
256,h2o: just add water,7.4,7.2,14782.0,SHOW,2009

In [ ]:
ratings_df[['netflix_score', 'imdb_score']].describe()

       netflix_score  imdb_score
count      83.000000   83.000000
mean        8.385542    7.433735
std         1.191344    1.089112
min         5.600000    3.900000
25%         7.700000    6.950000
50%         8.800000    7.600000
75%         9.400000    8.200000
max         9.900000    9.500000

Видно, что среднее значение рейтингов у imdb ниже, примерно на 1 пункт. То есть пользователи на imdb оценивают проекты строже чем на netflix. Это также видно по минимальной границе рейтинга: на imdb есть фильм с оценкой 3.9, на нетфликсе худший фильм имеет рейтинг 5.6. При этом максимальные значения отличаются не так сильно - лучшие фильмы хорошой оценивают на обоих площадках, но на нетфликсе лояльность аудитории все равно выше.

In [ ]:
ratings_df['diff'] = abs(ratings_df['imdb_score'] - ratings_df['netflix_score'])
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=ratings_df['imdb_score'],
    y=ratings_df['netflix_score'],
    mode='markers',
    marker=dict(size=10, color=ratings_df['diff'], colorscale='spectral'),
    text=ratings_df['title'],
    name='Оценки фильмов',
    hovertemplate = "<b>%{text}</b><br>IMDB: %{x}<br>Netflix: %{y}" #Это для красивого окошка при наведении на точку https://plotly.com/python/hover-text-and-formatting/
))

fig.add_trace(go.Scatter(
    x=[4, 10],
    y=[4, 10],
    mode='lines',
    name='Идеальная корреляция',
    line=dict(color='black', width=2, dash='dash')
))

fig.update_layout(
    title='Сравнение рейтингов Netflix и IMDB',
    xaxis_title='IMDB рейтинг',
    yaxis_title='Netflix рейтинг',
    showlegend=True
)


fig.show()
print('Корреляция рейтингов:', ratings_df['imdb_score'].corr(ratings_df['netflix_score']).round(2))

Корреляция рейтингов: 0.33

Хоть и числовая корреляция достаточно слабая - 0.33, по графику явно можно заметить зависимости данных. Точек выше пунктирной линии намного больше, чем точек ниже этой линии, так как аудитория нетфликса оценивает фильмы намного лояльнее. Также заметно что почти все данные выстроены по линиям, парралельным прямой y=x (то есть это графики y=x + c), особенно около этой прямой. Поэтому возможно, есть другие параметры, влияющие на расхождение рейтингов.

Посмотрим на количество голосов и разницу в рейтинге по фильмам. Возможно, чем больше голосов, тем более похожими будут рейтинги.

In [ ]:
fig = make_subplots(rows=1, cols=2, subplot_titles=('Обычный график', 'Логарифмированный график'))
ratings_df = ratings_df.sort_values(by='imdb_votes')
fig.add_trace(go.Scatter(
    x=ratings_df['imdb_votes'],
    y=ratings_df['diff'],
    mode='markers',
    name='Разница рейтингов',
    marker=dict(size=10),
    text=ratings_df['title'],
    hovertemplate='<b>%{text}</b><br>Голоса: %{x}<br>Разница: %{y}'), row=1, col=1
)

fig.add_trace(go.Scatter(
    x=np.log(ratings_df['imdb_votes']),
    y=ratings_df['diff'],
    mode='markers',
    name='Разница рейтингов',
    marker=dict(size=10),
    text=ratings_df['title'],
    hovertemplate='<b>%{text}</b><br>Голоса: %{x}<br>Разница: %{y}'), row=1, col=2
)

fig.update_xaxes(title_text="Количество голосов")
fig.update_yaxes(title_text="Разница в рейтинге")


fig.update_layout(
    title='Сравнение разницы рейтингов по количеству голосов',
    showlegend=False
)
fig.show()

Хоть и по  первому графику видно, что верхняя граница разницы в рейтинге уменьшается с увеличением количества голосов, 100 процентную зависимость доказать нельзя: слишком мало данных. Большинство тайтлов имееют малое количество голосов, поэтому я создал график, логарифмированный по оси x, и тут зависимость уже пропадает, что говорит о слабой корреляции количества голосов и рейтинга.

Теперь посмотрим на зависимость среднего рейтинга от типа контента

In [ ]:
gr_df = ratings_df.groupby('type')[['imdb_score', 'netflix_score']].mean().reset_index()
fig = px.bar(gr_df, x='type', y=['imdb_score', 'netflix_score'], barmode='group', title='Средние рейтинги по типу тайтла')

fig.show()

На графике различие в рейтинге между сериалами значительно меньше чем между фильмами. Это интересное наблюдение: аудитория, которая смотрит сериалы, скорее всего использует нетфликс, и ставит оценки на обоих площадках. Тогда как люди, ставящие оценки фильмам, могут посмотреть его как на нетфликсе, так и в кинотеатрах.

Из этого можно сделать вывод, что аудитория, которая смотрит сериалы очень похожа (в отличии от аудитории, которая оценивает фильмы), и при выпуске нового сериала можно расчитывать на равные оценки как на imdb, так и на netflix.

## Критерии оценки проекта

Оценка за групповой проект в целом — то есть первая из двух оценок — выставляется по 10-балльной шкале, исходя из 5 критериев. Также комиссия на своё усмотрение может добавить (но не снизить) некоторое количество бонусных баллов за рамками данных критериев.

Каждый из критериев будет перечислен и рассмотрен ниже.

### Критерий 1. Информативность техническая – необходимо выявить нетривиальные зависимости и тенденции в данных (до 2 баллов)

Данный критерий оценивает, насколько вы продвинулись технически с точки зрения выявления каких-то паттернов, тенденций и зависимостей в данных. Чем более сложные инструменты вы примените в ходе выполнения проекта и чем более сложные и нетривиальные зависимости получите, тем выше будет оценка у вашей команды по данному критерию!

### Критерий 2. Информативность аналитическая – необходимо интерпретировать данные и делать выводы, полезные для бизнеса  (до 2 баллов)

Данный критерий оценивает прикладной смысл проделанных вами действий, интерпретацию технических инструментов, умение подсветить полезность и значимость полученных выводов с точки зрения бизнеса, умение переложить полученные результаты на исходные бизнес-цели и "продать" то, что вы сделали.

### Критерий 3. Визуализация – оценивается техническое исполнение графиков (до 2 баллов)

Данный критерий оценивает сложность и техничность ваших визуализаций. Визуализации должны быть наглядными, красивыми, понятными, легко интерпертируемыми, нетривиальными с точки зрения технического исполнения и выводов, которые они несут в себе.


*Максимальный балл по данному критерию (**2 балла**) нельзя получить, если в работе используются лишь базовые библиотеки визуализаций: Matplotlib и Seaborn*

### Критерий 4. Предобработка датасета – очистка/замена данных (до 1 балла)

Данный критерий оценивает полноту всех проделанных действий с точки зрения подготовки данных и первичной предобработки датасета.

### Критерий 5. Обогащение данными – добавление новых признаков/датасетов (до 3 баллов)

Данный критерий оценивает полноту использования средств Feature Engineering на основе имеющихся данных, а также средств обогащения данных путем дополнения имеющегося датасета значимой информацией из связанных сторонних датасетов, различных внешних ресурсов и других источников. Обратите внимание, что информация извне **не должна замещать или подменять собой исходную задачу** и исходные данные в представленном датасете, а должна лишь дополнять и обогощать его. Корректность и глубина проработки взаимодействия со внешними ресурсами и оценивается в рамках данного критерия!

*Максимальный балл по данному критерию (**3 балла**) можно получить только при условии корректной и значимой работы с как минимум двумя источниками внешних данных (двумя внешними датасетами), а также при условии наличия как минимум двух примеров валидного и осмысленного применения средств Feature Egineering*

*По данному критерию можно получить **2 балла** только при условии корректной и значимой работы с как минимум одним источником внешних данных (внешним датасетом), а также при условии наличия как минимум одного примера валидного и осмысленного применения средств Feature Engineering*